name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install --production

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: <YOUR_SERVER_HOST>
          username: <YOUR_SERVER_USERNAME>
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./
          target: /path/to/your/app

      - name: Restart server
        run: ssh <YOUR_SERVER_USERNAME>@<YOUR_SERVER_HOST> "pm2 restart <YOUR_APP_NAME>"
